/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// AssetDBListerExpansion allows custom methods to be added to
// AssetDBLister.
type AssetDBListerExpansion interface{}

// AssetDBNamespaceListerExpansion allows custom methods to be added to
// AssetDBNamespaceLister.
type AssetDBNamespaceListerExpansion interface{}

// AssetDBListListerExpansion allows custom methods to be added to
// AssetDBListLister.
type AssetDBListListerExpansion interface{}

// AssetDBListNamespaceListerExpansion allows custom methods to be added to
// AssetDBListNamespaceLister.
type AssetDBListNamespaceListerExpansion interface{}

// DependencyListerExpansion allows custom methods to be added to
// DependencyLister.
type DependencyListerExpansion interface{}

// DependencyNamespaceListerExpansion allows custom methods to be added to
// DependencyNamespaceLister.
type DependencyNamespaceListerExpansion interface{}

// ShardListerExpansion allows custom methods to be added to
// ShardLister.
type ShardListerExpansion interface{}

// ShardNamespaceListerExpansion allows custom methods to be added to
// ShardNamespaceLister.
type ShardNamespaceListerExpansion interface{}

// ShardListListerExpansion allows custom methods to be added to
// ShardListLister.
type ShardListListerExpansion interface{}

// ShardListNamespaceListerExpansion allows custom methods to be added to
// ShardListNamespaceLister.
type ShardListNamespaceListerExpansion interface{}

// TrafficConfigListerExpansion allows custom methods to be added to
// TrafficConfigLister.
type TrafficConfigListerExpansion interface{}

// TrafficConfigNamespaceListerExpansion allows custom methods to be added to
// TrafficConfigNamespaceLister.
type TrafficConfigNamespaceListerExpansion interface{}
