/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AssetItemApplyConfiguration represents an declarative configuration of the AssetItem type for use
// with apply.
type AssetItemApplyConfiguration struct {
	Name        *string `json:"name,omitempty"`
	Environment *string `json:"environment,omitempty"`
}

// AssetItemApplyConfiguration constructs an declarative configuration of the AssetItem type for use with
// apply.
func AssetItem() *AssetItemApplyConfiguration {
	return &AssetItemApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AssetItemApplyConfiguration) WithName(value string) *AssetItemApplyConfiguration {
	b.Name = &value
	return b
}

// WithEnvironment sets the Environment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Environment field is set to the value of the last call.
func (b *AssetItemApplyConfiguration) WithEnvironment(value string) *AssetItemApplyConfiguration {
	b.Environment = &value
	return b
}
