/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ClusterShardsApplyConfiguration represents an declarative configuration of the ClusterShards type for use
// with apply.
type ClusterShardsApplyConfiguration struct {
	Name       *string                          `json:"name,omitempty"`
	Locality   *string                          `json:"locality,omitempty"`
	Identities []IdentityItemApplyConfiguration `json:"identities,omitempty"`
}

// ClusterShardsApplyConfiguration constructs an declarative configuration of the ClusterShards type for use with
// apply.
func ClusterShards() *ClusterShardsApplyConfiguration {
	return &ClusterShardsApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterShardsApplyConfiguration) WithName(value string) *ClusterShardsApplyConfiguration {
	b.Name = &value
	return b
}

// WithLocality sets the Locality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Locality field is set to the value of the last call.
func (b *ClusterShardsApplyConfiguration) WithLocality(value string) *ClusterShardsApplyConfiguration {
	b.Locality = &value
	return b
}

// WithIdentities adds the given value to the Identities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Identities field.
func (b *ClusterShardsApplyConfiguration) WithIdentities(values ...*IdentityItemApplyConfiguration) *ClusterShardsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithIdentities")
		}
		b.Identities = append(b.Identities, *values[i])
	}
	return b
}
