/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DependencySpecApplyConfiguration represents an declarative configuration of the DependencySpec type for use
// with apply.
type DependencySpecApplyConfiguration struct {
	Source        *string  `json:"source,omitempty"`
	IdentityLabel *string  `json:"identityLabel,omitempty"`
	Destinations  []string `json:"destinations,omitempty"`
}

// DependencySpecApplyConfiguration constructs an declarative configuration of the DependencySpec type for use with
// apply.
func DependencySpec() *DependencySpecApplyConfiguration {
	return &DependencySpecApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *DependencySpecApplyConfiguration) WithSource(value string) *DependencySpecApplyConfiguration {
	b.Source = &value
	return b
}

// WithIdentityLabel sets the IdentityLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityLabel field is set to the value of the last call.
func (b *DependencySpecApplyConfiguration) WithIdentityLabel(value string) *DependencySpecApplyConfiguration {
	b.IdentityLabel = &value
	return b
}

// WithDestinations adds the given value to the Destinations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Destinations field.
func (b *DependencySpecApplyConfiguration) WithDestinations(values ...string) *DependencySpecApplyConfiguration {
	for i := range values {
		b.Destinations = append(b.Destinations, values[i])
	}
	return b
}
