/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FailedClusterApplyConfiguration represents an declarative configuration of the FailedCluster type for use
// with apply.
type FailedClusterApplyConfiguration struct {
	Name             *string                            `json:"name,omitempty"`
	FailedIdentities []FailedIdentityApplyConfiguration `json:"identities,omitempty"`
}

// FailedClusterApplyConfiguration constructs an declarative configuration of the FailedCluster type for use with
// apply.
func FailedCluster() *FailedClusterApplyConfiguration {
	return &FailedClusterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FailedClusterApplyConfiguration) WithName(value string) *FailedClusterApplyConfiguration {
	b.Name = &value
	return b
}

// WithFailedIdentities adds the given value to the FailedIdentities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FailedIdentities field.
func (b *FailedClusterApplyConfiguration) WithFailedIdentities(values ...*FailedIdentityApplyConfiguration) *FailedClusterApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFailedIdentities")
		}
		b.FailedIdentities = append(b.FailedIdentities, *values[i])
	}
	return b
}
