/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShardStatusApplyConfiguration represents an declarative configuration of the ShardStatus type for use
// with apply.
type ShardStatusApplyConfiguration struct {
	ClustersMonitored *int                                     `json:"clustersMonitored,omitempty"`
	Conditions        []ShardStatusConditionApplyConfiguration `json:"conditions,omitempty"`
	FailureDetails    *FailureDetailsApplyConfiguration        `json:"failureDetails,omitempty"`
	LastUpdatedTime   *metav1.Time                             `json:"lastUpdateTime,omitempty"`
}

// ShardStatusApplyConfiguration constructs an declarative configuration of the ShardStatus type for use with
// apply.
func ShardStatus() *ShardStatusApplyConfiguration {
	return &ShardStatusApplyConfiguration{}
}

// WithClustersMonitored sets the ClustersMonitored field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClustersMonitored field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithClustersMonitored(value int) *ShardStatusApplyConfiguration {
	b.ClustersMonitored = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ShardStatusApplyConfiguration) WithConditions(values ...*ShardStatusConditionApplyConfiguration) *ShardStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithFailureDetails sets the FailureDetails field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureDetails field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithFailureDetails(value *FailureDetailsApplyConfiguration) *ShardStatusApplyConfiguration {
	b.FailureDetails = value
	return b
}

// WithLastUpdatedTime sets the LastUpdatedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdatedTime field is set to the value of the last call.
func (b *ShardStatusApplyConfiguration) WithLastUpdatedTime(value metav1.Time) *ShardStatusApplyConfiguration {
	b.LastUpdatedTime = &value
	return b
}
