/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShardStatusConditionApplyConfiguration represents an declarative configuration of the ShardStatusCondition type for use
// with apply.
type ShardStatusConditionApplyConfiguration struct {
	Message         *string             `json:"message,omitempty"`
	Reason          *v1.ConditionReason `json:"reason,omitempty"`
	Status          *v1.ConditionStatus `json:"status,omitempty"`
	Type            *v1.ConditionType   `json:"type,omitempty"`
	LastUpdatedTime *metav1.Time        `json:"lastUpdateTime,omitempty"`
}

// ShardStatusConditionApplyConfiguration constructs an declarative configuration of the ShardStatusCondition type for use with
// apply.
func ShardStatusCondition() *ShardStatusConditionApplyConfiguration {
	return &ShardStatusConditionApplyConfiguration{}
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ShardStatusConditionApplyConfiguration) WithMessage(value string) *ShardStatusConditionApplyConfiguration {
	b.Message = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ShardStatusConditionApplyConfiguration) WithReason(value v1.ConditionReason) *ShardStatusConditionApplyConfiguration {
	b.Reason = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ShardStatusConditionApplyConfiguration) WithStatus(value v1.ConditionStatus) *ShardStatusConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ShardStatusConditionApplyConfiguration) WithType(value v1.ConditionType) *ShardStatusConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithLastUpdatedTime sets the LastUpdatedTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdatedTime field is set to the value of the last call.
func (b *ShardStatusConditionApplyConfiguration) WithLastUpdatedTime(value metav1.Time) *ShardStatusConditionApplyConfiguration {
	b.LastUpdatedTime = &value
	return b
}
