# permissions for end users to edit shards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: shard-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: admiral-api
    app.kubernetes.io/part-of: admiral-api
    app.kubernetes.io/managed-by: kustomize
  name: shard-editor-role
rules:
- apiGroups:
  - admiral.io.admiral.io
  resources:
  - shards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admiral.io.admiral.io
  resources:
  - shards/status
  verbs:
  - get
