/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAssetDBLists implements AssetDBListInterface
type FakeAssetDBLists struct {
	Fake *FakeAdmiralV1
	ns   string
}

var assetdblistsResource = v1.SchemeGroupVersion.WithResource("assetdblists")

var assetdblistsKind = v1.SchemeGroupVersion.WithKind("AssetDBList")

// Get takes name of the assetDBList, and returns the corresponding assetDBList object, and an error if there is any.
func (c *FakeAssetDBLists) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AssetDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(assetdblistsResource, c.ns, name), &v1.AssetDBList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBList), err
}

// List takes label and field selectors, and returns the list of AssetDBLists that match those selectors.
func (c *FakeAssetDBLists) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AssetDBListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(assetdblistsResource, assetdblistsKind, c.ns, opts), &v1.AssetDBListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBListList), err
}

// Watch returns a watch.Interface that watches the requested assetDBLists.
func (c *FakeAssetDBLists) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(assetdblistsResource, c.ns, opts))

}

// Create takes the representation of a assetDBList and creates it.  Returns the server's representation of the assetDBList, and an error, if there is any.
func (c *FakeAssetDBLists) Create(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.CreateOptions) (result *v1.AssetDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(assetdblistsResource, c.ns, assetDBList), &v1.AssetDBList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBList), err
}

// Update takes the representation of a assetDBList and updates it. Returns the server's representation of the assetDBList, and an error, if there is any.
func (c *FakeAssetDBLists) Update(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.UpdateOptions) (result *v1.AssetDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(assetdblistsResource, c.ns, assetDBList), &v1.AssetDBList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBList), err
}

// Delete takes name of the assetDBList and deletes it. Returns an error if one occurs.
func (c *FakeAssetDBLists) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(assetdblistsResource, c.ns, name, opts), &v1.AssetDBList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAssetDBLists) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(assetdblistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.AssetDBListList{})
	return err
}

// Patch applies the patch and returns the patched assetDBList.
func (c *FakeAssetDBLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AssetDBList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(assetdblistsResource, c.ns, name, pt, data, subresources...), &v1.AssetDBList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBList), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied assetDBList.
func (c *FakeAssetDBLists) Apply(ctx context.Context, assetDBList *admiralv1.AssetDBListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDBList, err error) {
	if assetDBList == nil {
		return nil, fmt.Errorf("assetDBList provided to Apply must not be nil")
	}
	data, err := json.Marshal(assetDBList)
	if err != nil {
		return nil, err
	}
	name := assetDBList.Name
	if name == nil {
		return nil, fmt.Errorf("assetDBList.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(assetdblistsResource, c.ns, *name, types.ApplyPatchType, data), &v1.AssetDBList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AssetDBList), err
}
