/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDependencies implements DependencyInterface
type FakeDependencies struct {
	Fake *FakeAdmiralV1
	ns   string
}

var dependenciesResource = v1.SchemeGroupVersion.WithResource("dependencies")

var dependenciesKind = v1.SchemeGroupVersion.WithKind("Dependency")

// Get takes name of the dependency, and returns the corresponding dependency object, and an error if there is any.
func (c *FakeDependencies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Dependency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dependenciesResource, c.ns, name), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// List takes label and field selectors, and returns the list of Dependencies that match those selectors.
func (c *FakeDependencies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DependencyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dependenciesResource, dependenciesKind, c.ns, opts), &v1.DependencyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DependencyList{ListMeta: obj.(*v1.DependencyList).ListMeta}
	for _, item := range obj.(*v1.DependencyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dependencies.
func (c *FakeDependencies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dependenciesResource, c.ns, opts))

}

// Create takes the representation of a dependency and creates it.  Returns the server's representation of the dependency, and an error, if there is any.
func (c *FakeDependencies) Create(ctx context.Context, dependency *v1.Dependency, opts metav1.CreateOptions) (result *v1.Dependency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dependenciesResource, c.ns, dependency), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// Update takes the representation of a dependency and updates it. Returns the server's representation of the dependency, and an error, if there is any.
func (c *FakeDependencies) Update(ctx context.Context, dependency *v1.Dependency, opts metav1.UpdateOptions) (result *v1.Dependency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dependenciesResource, c.ns, dependency), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDependencies) UpdateStatus(ctx context.Context, dependency *v1.Dependency, opts metav1.UpdateOptions) (*v1.Dependency, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dependenciesResource, "status", c.ns, dependency), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// Delete takes name of the dependency and deletes it. Returns an error if one occurs.
func (c *FakeDependencies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dependenciesResource, c.ns, name, opts), &v1.Dependency{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDependencies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dependenciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DependencyList{})
	return err
}

// Patch applies the patch and returns the patched dependency.
func (c *FakeDependencies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Dependency, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dependenciesResource, c.ns, name, pt, data, subresources...), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dependency.
func (c *FakeDependencies) Apply(ctx context.Context, dependency *admiralv1.DependencyApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Dependency, err error) {
	if dependency == nil {
		return nil, fmt.Errorf("dependency provided to Apply must not be nil")
	}
	data, err := json.Marshal(dependency)
	if err != nil {
		return nil, err
	}
	name := dependency.Name
	if name == nil {
		return nil, fmt.Errorf("dependency.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dependenciesResource, c.ns, *name, types.ApplyPatchType, data), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDependencies) ApplyStatus(ctx context.Context, dependency *admiralv1.DependencyApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Dependency, err error) {
	if dependency == nil {
		return nil, fmt.Errorf("dependency provided to Apply must not be nil")
	}
	data, err := json.Marshal(dependency)
	if err != nil {
		return nil, err
	}
	name := dependency.Name
	if name == nil {
		return nil, fmt.Errorf("dependency.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dependenciesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.Dependency{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Dependency), err
}
