/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShardLists implements ShardListInterface
type FakeShardLists struct {
	Fake *FakeAdmiralV1
	ns   string
}

var shardlistsResource = v1.SchemeGroupVersion.WithResource("shardlists")

var shardlistsKind = v1.SchemeGroupVersion.WithKind("ShardList")

// Get takes name of the shardList, and returns the corresponding shardList object, and an error if there is any.
func (c *FakeShardLists) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ShardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shardlistsResource, c.ns, name), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardList), err
}

// List takes label and field selectors, and returns the list of ShardLists that match those selectors.
func (c *FakeShardLists) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ShardListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shardlistsResource, shardlistsKind, c.ns, opts), &v1.ShardListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardListList), err
}

// Watch returns a watch.Interface that watches the requested shardLists.
func (c *FakeShardLists) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shardlistsResource, c.ns, opts))

}

// Create takes the representation of a shardList and creates it.  Returns the server's representation of the shardList, and an error, if there is any.
func (c *FakeShardLists) Create(ctx context.Context, shardList *v1.ShardList, opts metav1.CreateOptions) (result *v1.ShardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shardlistsResource, c.ns, shardList), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardList), err
}

// Update takes the representation of a shardList and updates it. Returns the server's representation of the shardList, and an error, if there is any.
func (c *FakeShardLists) Update(ctx context.Context, shardList *v1.ShardList, opts metav1.UpdateOptions) (result *v1.ShardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shardlistsResource, c.ns, shardList), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardList), err
}

// Delete takes name of the shardList and deletes it. Returns an error if one occurs.
func (c *FakeShardLists) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(shardlistsResource, c.ns, name, opts), &v1.ShardList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShardLists) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shardlistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ShardListList{})
	return err
}

// Patch applies the patch and returns the patched shardList.
func (c *FakeShardLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ShardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shardlistsResource, c.ns, name, pt, data, subresources...), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardList), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied shardList.
func (c *FakeShardLists) Apply(ctx context.Context, shardList *admiralv1.ShardListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ShardList, err error) {
	if shardList == nil {
		return nil, fmt.Errorf("shardList provided to Apply must not be nil")
	}
	data, err := json.Marshal(shardList)
	if err != nil {
		return nil, err
	}
	name := shardList.Name
	if name == nil {
		return nil, fmt.Errorf("shardList.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shardlistsResource, c.ns, *name, types.ApplyPatchType, data), &v1.ShardList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ShardList), err
}
