/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrafficConfigs implements TrafficConfigInterface
type FakeTrafficConfigs struct {
	Fake *FakeAdmiralV1
	ns   string
}

var trafficconfigsResource = v1.SchemeGroupVersion.WithResource("trafficconfigs")

var trafficconfigsKind = v1.SchemeGroupVersion.WithKind("TrafficConfig")

// Get takes name of the trafficConfig, and returns the corresponding trafficConfig object, and an error if there is any.
func (c *FakeTrafficConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.TrafficConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trafficconfigsResource, c.ns, name), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// List takes label and field selectors, and returns the list of TrafficConfigs that match those selectors.
func (c *FakeTrafficConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TrafficConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trafficconfigsResource, trafficconfigsKind, c.ns, opts), &v1.TrafficConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TrafficConfigList{ListMeta: obj.(*v1.TrafficConfigList).ListMeta}
	for _, item := range obj.(*v1.TrafficConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trafficConfigs.
func (c *FakeTrafficConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trafficconfigsResource, c.ns, opts))

}

// Create takes the representation of a trafficConfig and creates it.  Returns the server's representation of the trafficConfig, and an error, if there is any.
func (c *FakeTrafficConfigs) Create(ctx context.Context, trafficConfig *v1.TrafficConfig, opts metav1.CreateOptions) (result *v1.TrafficConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trafficconfigsResource, c.ns, trafficConfig), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// Update takes the representation of a trafficConfig and updates it. Returns the server's representation of the trafficConfig, and an error, if there is any.
func (c *FakeTrafficConfigs) Update(ctx context.Context, trafficConfig *v1.TrafficConfig, opts metav1.UpdateOptions) (result *v1.TrafficConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trafficconfigsResource, c.ns, trafficConfig), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrafficConfigs) UpdateStatus(ctx context.Context, trafficConfig *v1.TrafficConfig, opts metav1.UpdateOptions) (*v1.TrafficConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trafficconfigsResource, "status", c.ns, trafficConfig), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// Delete takes name of the trafficConfig and deletes it. Returns an error if one occurs.
func (c *FakeTrafficConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(trafficconfigsResource, c.ns, name, opts), &v1.TrafficConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrafficConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trafficconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TrafficConfigList{})
	return err
}

// Patch applies the patch and returns the patched trafficConfig.
func (c *FakeTrafficConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TrafficConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficconfigsResource, c.ns, name, pt, data, subresources...), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trafficConfig.
func (c *FakeTrafficConfigs) Apply(ctx context.Context, trafficConfig *admiralv1.TrafficConfigApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrafficConfig, err error) {
	if trafficConfig == nil {
		return nil, fmt.Errorf("trafficConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(trafficConfig)
	if err != nil {
		return nil, err
	}
	name := trafficConfig.Name
	if name == nil {
		return nil, fmt.Errorf("trafficConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficconfigsResource, c.ns, *name, types.ApplyPatchType, data), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeTrafficConfigs) ApplyStatus(ctx context.Context, trafficConfig *admiralv1.TrafficConfigApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrafficConfig, err error) {
	if trafficConfig == nil {
		return nil, fmt.Errorf("trafficConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(trafficConfig)
	if err != nil {
		return nil, err
	}
	name := trafficConfig.Name
	if name == nil {
		return nil, fmt.Errorf("trafficConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficconfigsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.TrafficConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrafficConfig), err
}
