/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	scheme "github.com/istio-ecosystem/admiral-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AssetDBsGetter has a method to return a AssetDBInterface.
// A group's client should implement this interface.
type AssetDBsGetter interface {
	AssetDBs(namespace string) AssetDBInterface
}

// AssetDBInterface has methods to work with AssetDB resources.
type AssetDBInterface interface {
	Create(ctx context.Context, assetDB *v1.AssetDB, opts metav1.CreateOptions) (*v1.AssetDB, error)
	Update(ctx context.Context, assetDB *v1.AssetDB, opts metav1.UpdateOptions) (*v1.AssetDB, error)
	UpdateStatus(ctx context.Context, assetDB *v1.AssetDB, opts metav1.UpdateOptions) (*v1.AssetDB, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AssetDB, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AssetDBList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AssetDB, err error)
	Apply(ctx context.Context, assetDB *admiralv1.AssetDBApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDB, err error)
	ApplyStatus(ctx context.Context, assetDB *admiralv1.AssetDBApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDB, err error)
	AssetDBExpansion
}

// assetDBs implements AssetDBInterface
type assetDBs struct {
	client rest.Interface
	ns     string
}

// newAssetDBs returns a AssetDBs
func newAssetDBs(c *AdmiralV1Client, namespace string) *assetDBs {
	return &assetDBs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the assetDB, and returns the corresponding assetDB object, and an error if there is any.
func (c *assetDBs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AssetDB, err error) {
	result = &v1.AssetDB{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("assetdbs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AssetDBs that match those selectors.
func (c *assetDBs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AssetDBList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AssetDBList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("assetdbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested assetDBs.
func (c *assetDBs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("assetdbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a assetDB and creates it.  Returns the server's representation of the assetDB, and an error, if there is any.
func (c *assetDBs) Create(ctx context.Context, assetDB *v1.AssetDB, opts metav1.CreateOptions) (result *v1.AssetDB, err error) {
	result = &v1.AssetDB{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("assetdbs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(assetDB).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a assetDB and updates it. Returns the server's representation of the assetDB, and an error, if there is any.
func (c *assetDBs) Update(ctx context.Context, assetDB *v1.AssetDB, opts metav1.UpdateOptions) (result *v1.AssetDB, err error) {
	result = &v1.AssetDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("assetdbs").
		Name(assetDB.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(assetDB).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *assetDBs) UpdateStatus(ctx context.Context, assetDB *v1.AssetDB, opts metav1.UpdateOptions) (result *v1.AssetDB, err error) {
	result = &v1.AssetDB{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("assetdbs").
		Name(assetDB.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(assetDB).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the assetDB and deletes it. Returns an error if one occurs.
func (c *assetDBs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("assetdbs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *assetDBs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("assetdbs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched assetDB.
func (c *assetDBs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AssetDB, err error) {
	result = &v1.AssetDB{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("assetdbs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied assetDB.
func (c *assetDBs) Apply(ctx context.Context, assetDB *admiralv1.AssetDBApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDB, err error) {
	if assetDB == nil {
		return nil, fmt.Errorf("assetDB provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(assetDB)
	if err != nil {
		return nil, err
	}
	name := assetDB.Name
	if name == nil {
		return nil, fmt.Errorf("assetDB.Name must be provided to Apply")
	}
	result = &v1.AssetDB{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("assetdbs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *assetDBs) ApplyStatus(ctx context.Context, assetDB *admiralv1.AssetDBApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDB, err error) {
	if assetDB == nil {
		return nil, fmt.Errorf("assetDB provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(assetDB)
	if err != nil {
		return nil, err
	}

	name := assetDB.Name
	if name == nil {
		return nil, fmt.Errorf("assetDB.Name must be provided to Apply")
	}

	result = &v1.AssetDB{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("assetdbs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
