/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	scheme "github.com/istio-ecosystem/admiral-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AssetDBListsGetter has a method to return a AssetDBListInterface.
// A group's client should implement this interface.
type AssetDBListsGetter interface {
	AssetDBLists(namespace string) AssetDBListInterface
}

// AssetDBListInterface has methods to work with AssetDBList resources.
type AssetDBListInterface interface {
	Create(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.CreateOptions) (*v1.AssetDBList, error)
	Update(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.UpdateOptions) (*v1.AssetDBList, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AssetDBList, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AssetDBListList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AssetDBList, err error)
	Apply(ctx context.Context, assetDBList *admiralv1.AssetDBListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDBList, err error)
	AssetDBListExpansion
}

// assetDBLists implements AssetDBListInterface
type assetDBLists struct {
	client rest.Interface
	ns     string
}

// newAssetDBLists returns a AssetDBLists
func newAssetDBLists(c *AdmiralV1Client, namespace string) *assetDBLists {
	return &assetDBLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the assetDBList, and returns the corresponding assetDBList object, and an error if there is any.
func (c *assetDBLists) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AssetDBList, err error) {
	result = &v1.AssetDBList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("assetdblists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AssetDBLists that match those selectors.
func (c *assetDBLists) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AssetDBListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AssetDBListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("assetdblists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested assetDBLists.
func (c *assetDBLists) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("assetdblists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a assetDBList and creates it.  Returns the server's representation of the assetDBList, and an error, if there is any.
func (c *assetDBLists) Create(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.CreateOptions) (result *v1.AssetDBList, err error) {
	result = &v1.AssetDBList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("assetdblists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(assetDBList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a assetDBList and updates it. Returns the server's representation of the assetDBList, and an error, if there is any.
func (c *assetDBLists) Update(ctx context.Context, assetDBList *v1.AssetDBList, opts metav1.UpdateOptions) (result *v1.AssetDBList, err error) {
	result = &v1.AssetDBList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("assetdblists").
		Name(assetDBList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(assetDBList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the assetDBList and deletes it. Returns an error if one occurs.
func (c *assetDBLists) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("assetdblists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *assetDBLists) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("assetdblists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched assetDBList.
func (c *assetDBLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AssetDBList, err error) {
	result = &v1.AssetDBList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("assetdblists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied assetDBList.
func (c *assetDBLists) Apply(ctx context.Context, assetDBList *admiralv1.AssetDBListApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AssetDBList, err error) {
	if assetDBList == nil {
		return nil, fmt.Errorf("assetDBList provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(assetDBList)
	if err != nil {
		return nil, err
	}
	name := assetDBList.Name
	if name == nil {
		return nil, fmt.Errorf("assetDBList.Name must be provided to Apply")
	}
	result = &v1.AssetDBList{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("assetdblists").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
