/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/istio-ecosystem/admiral-api/pkg/apis/admiral/v1"
	admiralv1 "github.com/istio-ecosystem/admiral-api/pkg/client/applyconfiguration/admiral/v1"
	scheme "github.com/istio-ecosystem/admiral-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ShardsGetter has a method to return a ShardInterface.
// A group's client should implement this interface.
type ShardsGetter interface {
	Shards(namespace string) ShardInterface
}

// ShardInterface has methods to work with Shard resources.
type ShardInterface interface {
	Create(ctx context.Context, shard *v1.Shard, opts metav1.CreateOptions) (*v1.Shard, error)
	Update(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (*v1.Shard, error)
	UpdateStatus(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (*v1.Shard, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Shard, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ShardList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Shard, err error)
	Apply(ctx context.Context, shard *admiralv1.ShardApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Shard, err error)
	ApplyStatus(ctx context.Context, shard *admiralv1.ShardApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Shard, err error)
	ShardExpansion
}

// shards implements ShardInterface
type shards struct {
	client rest.Interface
	ns     string
}

// newShards returns a Shards
func newShards(c *AdmiralV1Client, namespace string) *shards {
	return &shards{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the shard, and returns the corresponding shard object, and an error if there is any.
func (c *shards) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Shard, err error) {
	result = &v1.Shard{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("shards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Shards that match those selectors.
func (c *shards) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ShardList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ShardList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("shards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested shards.
func (c *shards) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("shards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a shard and creates it.  Returns the server's representation of the shard, and an error, if there is any.
func (c *shards) Create(ctx context.Context, shard *v1.Shard, opts metav1.CreateOptions) (result *v1.Shard, err error) {
	result = &v1.Shard{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("shards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shard).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a shard and updates it. Returns the server's representation of the shard, and an error, if there is any.
func (c *shards) Update(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (result *v1.Shard, err error) {
	result = &v1.Shard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("shards").
		Name(shard.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shard).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *shards) UpdateStatus(ctx context.Context, shard *v1.Shard, opts metav1.UpdateOptions) (result *v1.Shard, err error) {
	result = &v1.Shard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("shards").
		Name(shard.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(shard).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the shard and deletes it. Returns an error if one occurs.
func (c *shards) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("shards").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *shards) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("shards").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched shard.
func (c *shards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Shard, err error) {
	result = &v1.Shard{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("shards").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied shard.
func (c *shards) Apply(ctx context.Context, shard *admiralv1.ShardApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Shard, err error) {
	if shard == nil {
		return nil, fmt.Errorf("shard provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(shard)
	if err != nil {
		return nil, err
	}
	name := shard.Name
	if name == nil {
		return nil, fmt.Errorf("shard.Name must be provided to Apply")
	}
	result = &v1.Shard{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("shards").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *shards) ApplyStatus(ctx context.Context, shard *admiralv1.ShardApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Shard, err error) {
	if shard == nil {
		return nil, fmt.Errorf("shard provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(shard)
	if err != nil {
		return nil, err
	}

	name := shard.Name
	if name == nil {
		return nil, fmt.Errorf("shard.Name must be provided to Apply")
	}

	result = &v1.Shard{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("shards").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
